<?xml version="1.0"?>
<package format="3">
  <name>arha_tcp_driver</name>
  <version>0.1.0</version>
  <description>Plain C++ TCP driver library for communicating with the ARHA robot STM32 controller</description>
  <maintainer email="kennethaldahir.martinezmoreno@ontariotechu.net">Kenneth Martinez</maintainer>
  <license>MIT</license>

  <buildtool_depend>cmake</buildtool_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
